// Code generated by protoc-gen-go.
// source: grpc.proto
// DO NOT EDIT!

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	grpc.proto

It has these top-level messages:
	SetRequest
	GetRequest
	Response
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetRequest struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *SetRequest) Reset()                    { *m = SetRequest{} }
func (m *SetRequest) String() string            { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()               {}
func (*SetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SetRequest)(nil), "main.SetRequest")
	proto.RegisterType((*GetRequest)(nil), "main.GetRequest")
	proto.RegisterType((*Response)(nil), "main.Response")
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2f, 0x2a, 0x48,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x32, 0xe3, 0xe2,
	0x0a, 0x4e, 0x2d, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b,
	0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x44, 0xb8, 0x58, 0xcb,
	0x12, 0x73, 0x4a, 0x53, 0x25, 0x98, 0xc0, 0x82, 0x10, 0x8e, 0x92, 0x02, 0x17, 0x97, 0x3b, 0x5e,
	0x7d, 0x4a, 0x2a, 0x5c, 0x1c, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x12, 0x5c,
	0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0x30, 0x25, 0x30, 0xae, 0x51, 0x2f, 0x23, 0x17, 0x7b,
	0x70, 0x49, 0x7e, 0x51, 0x62, 0x7a, 0xaa, 0x90, 0x26, 0x17, 0xb3, 0x7b, 0x6a, 0x89, 0x90, 0x80,
	0x1e, 0xc8, 0x65, 0x7a, 0x08, 0xe3, 0xa5, 0xf8, 0x20, 0x22, 0x30, 0xe3, 0x94, 0x18, 0x40, 0x4a,
	0x83, 0x11, 0x4a, 0x83, 0xf1, 0x29, 0xd5, 0xe1, 0x62, 0x73, 0x49, 0xcd, 0x49, 0x2d, 0x49, 0x25,
	0xc6, 0x60, 0x27, 0xce, 0x28, 0x76, 0x3d, 0x3d, 0x7d, 0x50, 0x30, 0x25, 0xb1, 0x81, 0xc3, 0xc9,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xdd, 0xac, 0xb8, 0x35, 0x01, 0x00, 0x00,
}
